# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirstPhase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirstPhase

use_frameworks!

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
pod 'Firebase/Firestore'
pod 'Firebase/Functions'
pod 'FirebaseFirestoreSwift'
pod 'Firebase/Core'
pod 'Firebase/Crashlytics'

  target 'FirstPhaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirstPhaseUITests' do
    # Pods for testing
  end

end
